name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/auth
            git pull origin main
            git fetch --tags origin
            VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.1")
            go build -ldflags "-X gilosauth/config.Version=$VERSION" main.go
            sudo systemctl restart auth
